// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paohzlivrrfabirfrcbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhb2h6bGl2cnJmYWJpcmZyY2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjEzMDUsImV4cCI6MjA2MzgzNzMwNX0.8_nc-KZ4Z3FQCSRlQwRaeYuBhtWis04inxas4hmQALs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);